# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: tabledb
val_db_name: tabledb
num_classes: 3
temperature: 0.07

# Loss
criterion: simclr
criterion_kwargs:
   temperature: 0.07


# Hyperparameters
epochs: 60
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001
   momentum: 0.9
   lr: 0.03
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 6
num_workers: 0

# Transformations
augmentation_strategy: tabledb
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale:
      p: 0.2
   normalize:
      mean: [0.953, 0.953, 0.953]
      std: [0.136, 0.136, 0.136]


transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.953, 0.953, 0.953]
      std: [0.136, 0.136, 0.136]
