# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: tabledb
val_db_name: tabledb
num_classes: 3
temperature: 0.07

# Batch size and workers
batch_size: 2
num_workers: 0

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.953, 0.953, 0.953]
      std: [0.136, 0.136, 0.136]
